- id: '1546637638735'
  alias: Kenkienkuivaimen sammutusajastin
  trigger:
  - entity_id: switch.05200020ecfabc935097
    for: 01:00:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.05200020ecfabc935097
    service: switch.turn_off
