homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 62.519139
  longitude: 26.040333
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  # Customization file
  customize: !include customize.yaml

http:
  base_url: https://savela.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    name: ennuste 6h
    forecast: 6
    monitored_conditions:
    - temperature
    - symbol
  # outdoor temperature
  - platform: mqtt
    name: "ulkolämpö"
    device_class: temperature
    state_topic: "NexusTemperatureHumidity/123/temperature"
    unit_of_measurement: 'C'
  # outdoor humidity
  - platform: mqtt
    name: "ulkokosteus"
    device_class: humidity
    state_topic: "NexusTemperatureHumidity/123/humidity"
    unit_of_measurement: '%'
  # indoor temperature
  - platform: mqtt
    name: "huonelämpö1"
    device_class: temperature
    state_topic: "NexusTemperatureHumidity/130/temperature"
    unit_of_measurement: 'C'
  # outdoor humidity
  - platform: mqtt
    name: "huonekosteus1"
    device_class: humidity
    state_topic: "NexusTemperatureHumidity/130/humidity"
    unit_of_measurement: '%'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# tuya
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 358

neato:
  username: !secret neato_username
  password: !secret neato_password
  
vacuum:
  - platform: neato
    name: Donald
    host: 192.168.1.108  
    
notify:
  - platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
    

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
